### ISSUE TITLE
Optionally use github.com/klauspost/compress

### ISSUE THREAD

**Issue by AlekSi** [qedus/osmpbf#13]
https://github.com/klauspost/compress looks impressive.

I propose to create a subpackage (`github.com/qedus/osmpbf/faster`? :) ) which imports `github.com/klauspost/compress` and uses a simple dependency injection to use it.

Going to do it myself in few weeks. If someone can't wait – go ahead, do it. :)

**Comment by jongillham** [comment]
As far as I can see `github.com/klauspost/compress` only works for compressing not decompressing. `osmpbf` only uses decompression right now. Maybe I am confused as to how you want to use it.

**Comment by AlekSi** [comment]
Yeah, you are right, I was overexcited.

> Currently there is only minor speedup on decompression (primarily CRC32 calculation).
