### ISSUE TITLE
Support OSC files (replication change files)

### ISSUE THREAD

**Issue by Iulian7** [qedus/osmpbf#22]
Are there any plans to support parsing `.osc` files like those used for the planet replication (e.g. https://planet.openstreetmap.org/replication/hour/000/)?

**Comment by jongillham** [comment]
Hi @lulian7, this package is specifically for supporting the Protocol Buffer (PBF) format. I see the '.osc' file format uses XML for the change descriptions. Therefore I think it is unlikely that this package will support '.osc' files unless I am mistaken.
