### ISSUE TITLE
Should we tag v1.0.0?

### ISSUE THREAD

**Issue by AlekSi** [qedus/osmpbf#23]
Personally, I think this package is good enough for SemVer v1.0.0. Maintaining backward compatibility should be possible.

**Comment by jongillham** [comment]
I'm happy with that. What would you change if you were to redo the API?

**Comment by AlekSi** [comment]
I can't think of anything that can break existing public API.

**Comment by AlekSi** [comment]
So. Should I tag it `v1.0.0`?

**Comment by jongillham** [comment]
Please do!

**Comment by AlekSi** [comment]
Done.
