### ISSUE TITLE
Could use a vendoring tool like dep for vendoring

### ISSUE THREAD

**Issue by clydedacruz** [qedus/osmpbf#31]
**Installation**
The `dep` cmd line tool can be installed using 
`$ curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh`

OR

`go install github.com/golang/dep/cmd/dep`  (make sure gopath/bin is added to path if using this approach)

**Migrating to `dep`**

```
cd osmpbf
dep init
```
`dep init` will make educated guesses about what versions to use for your dependencies and generate sane Gopkg.toml, Gopkg.lock, and vendor/

**Fetch all project dependencies after cloning a project**
`dep ensure`  
This command updates the `vendor/` folder to have all the required dependencies.

**Comment by AlekSi** [comment]
As long as osmpbf library can be installed with `go get -u` (that is, using the latest `master` versions of all dependencies), I don't think we should use vendoring for library package. osmpbf users (applications) are encouraged to use vendoring with dep, however.

**Comment by clydedacruz** [comment]
ok. Ur right, it would be overkill to use dep at this point. Can close this.
