### ISSUE TITLE
import "code.google.com/p/goprotobuf/proto"

### ISSUE THREAD

**Issue by kkdd** [qedus/osmpbf#9]
I found the following error when executing a program:
```>> cannot find package "code.google.com/p/goprotobuf/proto"```

And I have successfully run the program by modifying as follows:
```
- import "code.google.com/p/goprotobuf/proto"
+ import "github.com/golang/protobuf/proto"
```

**Comment by jongillham** [comment]
Commit bff90e1 fixes this.
